istio:
  enabled: false
ingressgateway:
  host: spring-boot-demo2-istio-ingress.apps.cluster-tlkwm.dynamic.redhatworkshops.io
fullnameOverride: spring-boot-demo2
replicaCount: 1
cryostat:
  agent:
    enabled: false
  jmx:
    enabled: true
