ingressgateway:
  name: ingressgateway
  namespace: another-istio-ingress
context: 
  name: golang-ex
  namespace: golang-ex
features:
  stable:
    svc: golang-ex-stable
    host: golang-ex-stable-another-istio-ingress.apps.cluster-tlkwm.dynamic.redhatworkshops.io
  high:
    svc: golang-ex-high
    host: golang-ex-high-another-istio-ingress.apps.cluster-tlkwm.dynamic.redhatworkshops.io
  featurea:
    svc: golang-ex-featurea
    host: golang-ex-featurea-another-istio-ingress.apps.cluster-tlkwm.dynamic.redhatworkshops.io
