istio:
  enabled: true
ingressgateway:
  host: spring-boot-demo-istio-ingress.apps.cluster-mqlh6.dynamic.redhatworkshops.io
replicaCount: 3
cryostat:
  agent:
    enabled: false
  jmx:
    enabled: true
