cookieSecret: supersecret
datasource:
  url: 'http://prometheus-server.prometheus.svc.cluster.local'
  jsonData:
    customQueryParameters:
consoleLink: 
  enabled: true
  route: "https://grafana-instance-route-grafana.apps.cluster-mqlh6.dynamic.redhatworkshops.io"
