smcp:
  name: ossm2
  namespace: istio-system
ingressgateway:
  namespace: istio-ingress
deployment:
  namespace: kiali
consoleLink: 
  enabled: true
  route: "https://kiali-ossm2-istio-system-kiali.apps.cluster-mqlh6.dynamic.redhatworkshops.io"
grafana:
  url: https://grafana-instance-route-grafana.apps.cluster-mqlh6.dynamic.redhatworkshops.io
  in_cluster_url: http://grafana-instance-service.grafana.svc:3000
tracing:
  url: https://jaeger-ui-proxy-tempo-system.apps.cluster-mqlh6.dynamic.redhatworkshops.io
prometheus:
  url: http://prometheus-server.prometheus.svc.cluster.local
  auth: 
  query_scope:
